version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres16
    environment:
      POSTGRES_USER: jbarranco
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

